include:
  - project: 'BungaaFACE/home-lab'
    file: 
      - 'pipeline-includes/templates.yml'
      - 'pipeline-includes/variables.yml'

stages:
  - build
  - deploy

build_bungaacord_backend:
  extends: .triggered_template
  tags:
    - shell
  stage: build
  needs: []
  script:
    - docker build -f docker/bungaacord_backend.dockerfile -t localhost:5000/bungaacord-backend:latest .
    - docker push localhost:5000/bungaacord-backend:latest

build_bungaacord_frontend:
  extends: .triggered_template
  tags:
    - shell
  stage: build
  needs: []
  script:
    - docker build -f docker/bungaacord_frontend.dockerfile -t localhost:5000/bungaacord-frontend:latest .
    - docker push localhost:5000/bungaacord-frontend:latest

deploy_bungaacord_backend:
  extends: 
    - .compose_deploy_template
    - .nginx_site_deploy_template
    - .triggered_template
  needs: []
  before_script:
    - mkdir -p ${SITES_PATH}
    - mkdir -p ${DATA_PATH}/bungaacord_backend
    - touch ${DATA_PATH}/bungaacord_backend/app.db
  variables:
    COMPOSE_FILE_DIR: "docker/"
    COMPOSE_FILE: "compose_bungaacord_backend.yaml"
    NGINX_FILE_DIR: "docker/"
    NGINX_FILE: "nginx_bungaacord_backend.conf"
    DOMAIN_NAME: "bungaacord-backend.bungaa-server.ru"

deploy_bungaacord_frontend:
  extends: 
    - .compose_deploy_template
    - .nginx_site_deploy_template
    - .triggered_template
  needs: []
  variables:
    COMPOSE_FILE_DIR: "docker/"
    COMPOSE_FILE: "compose_bungaacord_frontend.yaml"
    NGINX_FILE_DIR: "docker/"
    NGINX_FILE: "nginx_bungaacord_frontend.conf"
    DOMAIN_NAME: "bungaacord.bungaa-server.ru"
    BACKEND_DOMAIN_NAME: "https://bungaacord-backend.bungaa-server.ru"